services:
  db_vets:
    image: mysql:lts
    ports:
      - ${HOST_DB_PORT:-3308}:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_vets_data:/var/lib/mysql
    networks:
      - fullstack_default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT:-8092}:80
    env_file:
      - .env
    environment:
      PMA_HOST: db_vets
      PMA_PORT: 3306
    networks:
      - fullstack_default
    depends_on:
      - db_vets

volumes:
  mysql_vets_data:

networks:
  fullstack_default:
    name: fullstack_default
