# Documentation Metadata
springdoc.openapi.info.title=Vets Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=Microservicio de gestión de veterinarios. \
                                   Expone operaciones CRUD de veterinarios y horarios.
